name: Upload website

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: s55.zenbox.pl
          username: harmonj2
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/harmonja.edu.pl/public_html/
